// Items
export const REQ_ITEMS_PENDING = 'REQ_ITEMS_PENDING';
export const REQ_ITEMS_SUCCESS = 'REQ_ITEMS_SUCCESS';
export const REQ_ITEMS_ERROR = 'REQ_ITEMS_ERROR';

export const REQ_ITEM_PENDING = 'REQ_ITEM_PENDING';
export const REQ_ITEM_SUCCESS = 'REQ_ITEM_SUCCESS';
export const REQ_ITEM_ERROR = 'REQ_ITEM_ERROR';

export const ADD_ITEM_PENDING = 'ADD_ITEM_PENDING';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const UPDATE_ITEM_PENDING = 'UPDATE_ITEM_PENDING';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR';

export const DELETE_ITEM_PENDING = 'DELETE_ITEM_PENDING';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';
