// Items
export const REQ_ITEMS_PENDING = 'REQ_ITEMS_PENDING';
export const REQ_ITEMS_SUCCESS = 'REQ_ITEMS_SUCCESS';
export const REQ_ITEMS_ERROR = 'REQ_ITEMS_ERROR';

export const REQ_ITEM_PENDING = 'REQ_ITEM_PENDING';
export const REQ_ITEM_SUCCESS = 'REQ_ITEM_SUCCESS';
export const REQ_ITEM_ERROR = 'REQ_ITEM_ERROR';

export const ADD_ITEM_PENDING = 'ADD_ITEM_PENDING';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const UPDATE_ITEM_PENDING = 'UPDATE_ITEM_PENDING';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR';

export const DELETE_ITEM_PENDING = 'DELETE_ITEM_PENDING';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

// users
export const REQ_USERS_PENDING = 'REQ_USERS_PENDING';
export const REQ_USERS_SUCCESS = 'REQ_USERS_SUCCESS';
export const REQ_USERS_ERROR = 'REQ_USERS_ERROR';

export const REQ_USER_PENDING = 'REQ_USER_PENDING';
export const REQ_USER_SUCCESS = 'REQ_USER_SUCCESS';
export const REQ_USER_ERROR = 'REQ_USER_ERROR';

export const ADD_USER_PENDING = 'ADD_USER_PENDING';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

// pokemon
export const REQ_POKEMONS_PENDING = 'REQ_POKEMONS_PENDING';
export const REQ_POKEMONS_SUCCESS = 'REQ_POKEMONS_SUCCESS';
export const REQ_POKEMONS_ERROR = 'REQ_POKEMONS_ERROR';

export const REQ_POKEMON_PENDING = 'REQ_POKEMON_PENDING';
export const REQ_POKEMON_SUCCESS = 'REQ_POKEMON_SUCCESS';
export const REQ_POKEMON_ERROR = 'REQ_POKEMON_ERROR';

export const ADD_POKEMON_PENDING = 'ADD_POKEMON_PENDING';
export const ADD_POKEMON_SUCCESS = 'ADD_POKEMON_SUCCESS';
export const ADD_POKEMON_ERROR = 'ADD_POKEMON_ERROR';

export const UPDATE_POKEMON_PENDING = 'UPDATE_POKEMON_PENDING';
export const UPDATE_POKEMON_SUCCESS = 'UPDATE_POKEMON_SUCCESS';
export const UPDATE_POKEMON_ERROR = 'UPDATE_POKEMON_ERROR';

export const DELETE_POKEMON_PENDING = 'DELETE_POKEMON_PENDING';
export const DELETE_POKEMON_SUCCESS = 'DELETE_POKEMON_SUCCESS';
export const DELETE_POKEMON_ERROR = 'DELETE_POKEMON_ERROR';

// AUTH ACTION TYPES
export const SET_LOGGED_IN = 'SET_LOGGED_IN';

// usermons
export const REQ_USERMONS_PENDING = 'REQ_USERMONS_PENDING';
export const REQ_USERMONS_SUCCESS = 'REQ_USERMONS_SUCCESS';
export const REQ_USERMONS_ERROR = 'REQ_USERMONS_ERROR';

export const REQ_USERMON_PENDING = 'REQ_USERMON_PENDING';
export const REQ_USERMON_SUCCESS = 'REQ_USERMON_SUCCESS';
export const REQ_USERMON_ERROR = 'REQ_USERMON_ERROR';

export const ADD_USERMON_PENDING = 'ADD_USERMON_PENDING';
export const ADD_USERMON_SUCCESS = 'ADD_USERMON_SUCCESS';
export const ADD_USERMON_ERROR = 'ADD_USERMON_ERROR';

export const UPDATE_USERMON_PENDING = 'UPDATE_USERMON_PENDING';
export const UPDATE_USERMON_SUCCESS = 'UPDATE_USERMON_SUCCESS';
export const UPDATE_USERMON_ERROR = 'UPDATE_USERMON_ERROR';

export const DELETE_USERMON_PENDING = 'DELETE_USERMON_PENDING';
export const DELETE_USERMON_SUCCESS = 'DELETE_USERMON_SUCCESS';
export const DELETE_USERMON_ERROR = 'DELETE_USERMON_ERROR';

// moves
export const REQ_MOVES_PENDING = 'REQ_MOVES_PENDING';
export const REQ_MOVES_SUCCESS = 'REQ_MOVES_SUCCESS';
export const REQ_MOVES_ERROR = 'REQ_MOVES_ERROR';

export const REQ_MOVE_PENDING = 'REQ_MOVE_PENDING';
export const REQ_MOVE_SUCCESS = 'REQ_MOVE_SUCCESS';
export const REQ_MOVE_ERROR = 'REQ_MOVE_ERROR';

export const ADD_MOVE_PENDING = 'ADD_MOVE_PENDING';
export const ADD_MOVE_SUCCESS = 'ADD_MOVE_SUCCESS';
export const ADD_MOVE_ERROR = 'ADD_MOVE_ERROR';

export const UPDATE_MOVE_PENDING = 'UPDATE_MOVE_PENDING';
export const UPDATE_MOVE_SUCCESS = 'UPDATE_MOVE_SUCCESS';
export const UPDATE_MOVE_ERROR = 'UPDATE_MOVE_ERROR';

export const DELETE_MOVE_PENDING = 'DELETE_MOVE_PENDING';
export const DELETE_MOVE_SUCCESS = 'DELETE_MOVE_SUCCESS';
export const DELETE_MOVE_ERROR = 'DELETE_MOVE_ERROR';

// balls
export const REQ_BALLS_PENDING = 'REQ_BALLS_PENDING';
export const REQ_BALLS_SUCCESS = 'REQ_BALLS_SUCCESS';
export const REQ_BALLS_ERROR = 'REQ_BALLS_ERROR';

export const REQ_BALL_PENDING = 'REQ_BALL_PENDING';
export const REQ_BALL_SUCCESS = 'REQ_BALL_SUCCESS';
export const REQ_BALL_ERROR = 'REQ_BALL_ERROR';

export const ADD_BALL_PENDING = 'ADD_BALL_PENDING';
export const ADD_BALL_SUCCESS = 'ADD_BALL_SUCCESS';
export const ADD_BALL_ERROR = 'ADD_BALL_ERROR';

export const UPDATE_BALL_PENDING = 'UPDATE_BALL_PENDING';
export const UPDATE_BALL_SUCCESS = 'UPDATE_BALL_SUCCESS';
export const UPDATE_BALL_ERROR = 'UPDATE_BALL_ERROR';

export const DELETE_BALL_PENDING = 'DELETE_BALL_PENDING';
export const DELETE_BALL_SUCCESS = 'DELETE_BALL_SUCCESS';
export const DELETE_BALL_ERROR = 'DELETE_BALL_ERROR';

// types
export const REQ_TYPES_PENDING = 'REQ_TYPES_PENDING';
export const REQ_TYPES_SUCCESS = 'REQ_TYPES_SUCCESS';
export const REQ_TYPES_ERROR = 'REQ_TYPES_ERROR';

export const REQ_TYPE_PENDING = 'REQ_TYPE_PENDING';
export const REQ_TYPE_SUCCESS = 'REQ_TYPE_SUCCESS';
export const REQ_TYPE_ERROR = 'REQ_TYPE_ERROR';

export const ADD_TYPE_PENDING = 'ADD_TYPE_PENDING';
export const ADD_TYPE_SUCCESS = 'ADD_TYPE_SUCCESS';
export const ADD_TYPE_ERROR = 'ADD_TYPE_ERROR';

export const UPDATE_TYPE_PENDING = 'UPDATE_TYPE_PENDING';
export const UPDATE_TYPE_SUCCESS = 'UPDATE_TYPE_SUCCESS';
export const UPDATE_TYPE_ERROR = 'UPDATE_TYPE_ERROR';

export const DELETE_TYPE_PENDING = 'DELETE_TYPE_PENDING';
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS';
export const DELETE_TYPE_ERROR = 'DELETE_TYPE_ERROR';

// conversations
export const REQ_CONVERSATIONS_PENDING = 'REQ_CONVERSATIONS_PENDING';
export const REQ_CONVERSATIONS_SUCCESS = 'REQ_CONVERSATIONS_SUCCESS';
export const REQ_CONVERSATIONS_ERROR = 'REQ_CONVERSATIONS_ERROR';

export const REQ_CONVERSATION_PENDING = 'REQ_CONVERSATION_PENDING';
export const REQ_CONVERSATION_SUCCESS = 'REQ_CONVERSATION_SUCCESS';
export const REQ_CONVERSATION_ERROR = 'REQ_CONVERSATION_ERROR';

export const ADD_CONVERSATION_PENDING = 'ADD_CONVERSATION_PENDING';
export const ADD_CONVERSATION_SUCCESS = 'ADD_CONVERSATION_SUCCESS';
export const ADD_CONVERSATION_ERROR = 'ADD_CONVERSATION_ERROR';

export const UPDATE_CONVERSATION_PENDING = 'UPDATE_CONVERSATION_PENDING';
export const UPDATE_CONVERSATION_SUCCESS = 'UPDATE_CONVERSATION_SUCCESS';
export const UPDATE_CONVERSATION_ERROR = 'UPDATE_CONVERSATION_ERROR';

export const DELETE_CONVERSATION_PENDING = 'DELETE_CONVERSATION_PENDING';
export const DELETE_CONVERSATION_SUCCESS = 'DELETE_CONVERSATION_SUCCESS';
export const DELETE_CONVERSATION_ERROR = 'DELETE_CONVERSATION_ERROR';
